sudo: required
services:
  - docker

before_install:
  - docker build -t docker1200/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker1200/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-358307482571"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY 